export const USER_ROLES = ["CUSTOMER", "RIDER", "BUSINESS", "ADMIN"] as const;

export const ORDER_STATUSES = [
  "CREATED",
  "QUOTED",
  "ASSIGNING_RIDER",
  "RIDER_ASSIGNED",
  "RIDER_EN_ROUTE",
  "ARRIVED_PICKUP",
  "PICKED_UP",
  "IN_TRANSIT",
  "ARRIVED_DROPOFF",
  "DELIVERED",
  "FAILED_PICKUP",
  "FAILED_DELIVERY",
  "DISPUTED",
  "CLOSED",
  "CANCELLED",
] as const;

export const QUOTE_STATUSES = [
  "QUOTE_CREATED",
  "QUOTE_VIEWED",
  "QUOTE_ACCEPTED",
  "QUOTE_ABANDONED",
  "QUOTE_EXPIRED",
  "QUOTE_REFRESHED",
] as const;

export const PROOF_TYPES = [
  "PICKUP_OTP",
  "DELIVERY_OTP",
  "PHOTO_PROOF",
  "RECIPIENT_CONFIRMATION",
  "RIDER_NOTE",
  "ADMIN_OVERRIDE",
] as const;

export const SUPPORT_CATEGORIES = [
  "TRACK_ORDER",
  "PRICING_QUESTION",
  "FAILED_PICKUP",
  "FAILED_DELIVERY",
  "DAMAGE_CLAIM",
  "LOST_ITEM",
  "PAYMENT",
  "CANCELLATION",
  "BUSINESS_SUPPORT",
  "RIDER_SUPPORT",
  "SAFETY_REPORT",
] as const;
